## MLP Classifier

In [1]:
from sklearn.datasets import load_iris
iris = load_iris()

In [2]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [3]:
iris['data'].shape

(150, 4)

In [4]:
data = iris['data']
target = iris['target']

In [5]:
from sklearn.model_selection import train_test_split
data_train, data_test, target_train, target_test = train_test_split(data, target)

In [6]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(data_train)

StandardScaler()

In [7]:
data_train = scaler.transform(data_train)
data_test = scaler.transform(data_test)

In [8]:
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(5, 2), random_state=1, max_iter=150, tol=0.001)

print(clf.fit(data_train,target_train))

MLPClassifier(alpha=1e-05, hidden_layer_sizes=(5, 2), max_iter=150,
              random_state=1, solver='lbfgs', tol=0.001)


In [9]:
predictions = clf.predict(data_test)

In [10]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(target_test,predictions))

[[10  0  0]
 [ 0 16  0]
 [ 0  2 10]]


In [11]:
print(classification_report(target_test,predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.89      1.00      0.94        16
           2       1.00      0.83      0.91        12

    accuracy                           0.95        38
   macro avg       0.96      0.94      0.95        38
weighted avg       0.95      0.95      0.95        38



## MLP Regression

In [12]:
from keras.datasets import mnist 
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [13]:
print("Number of training examples :", X_train.shape[0], "and each image is of shape (%d, %d)"%(X_train.shape[1], X_train.shape[2]))
print("Number of training examples :", X_test.shape[0], "and each image is of shape (%d, %d)"%(X_test.shape[1], X_test.shape[2]))

Number of training examples : 60000 and each image is of shape (28, 28)
Number of training examples : 10000 and each image is of shape (28, 28)


In [14]:
X_train = X_train.reshape(X_train.shape[0], X_train.shape[1]*X_train.shape[2]) 
X_test = X_test.reshape(X_test.shape[0], X_test.shape[1]*X_test.shape[2])

In [15]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
scaler.fit(X_test)
X_test = scaler.transform(X_test)

In [18]:
from sklearn.neural_network import MLPRegressor
reg = MLPRegressor(hidden_layer_sizes=(64,64,64),activation="relu" ,random_state=1, max_iter=2000).fit(X_train, y_train)

In [22]:
from sklearn.metrics import r2_score
y_pred=reg.predict(X_test)
print("The Score with ", (r2_score(y_pred, y_test)))

The Score with  0.9595947799559512
