In [1]:
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.model_selection import train_test_split as sklearn_train_test_split
from sklearn.datasets import load_iris
from lib.rbfnn import RBF 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

### Dataset 1

In [2]:
from sklearn.datasets import load_iris
data=load_iris()

In [3]:
x1 = data['data']
y1 = data['target']


x1_train, x1_test, y1_train, y1_test =sklearn_train_test_split(x1, y1, test_size=0.3, random_state=42)

In [4]:
rbf = RBF(6) 
rbf.fit(x1_train,y1_train)
result1 = rbf.predict(x1_test)

print('accuracy: ',accuracy_score(result1,y1_test))
print('confusion_matrix: \n',confusion_matrix(result1,y1_test))

accuracy:  0.8
confusion_matrix: 
 [[19  0  0]
 [ 0  4  0]
 [ 0  9 13]]


### Dataset 2

In [5]:
Data= pd.read_table("bank-full.csv", sep= None, engine= "python")
cols= ["age","balance","day","duration","campaign","pdays","previous"]

In [6]:
data_encode= Data.drop(cols, axis= 1)
data_encode= data_encode.apply(LabelEncoder().fit_transform)
data_rest= Data[cols]
Data= pd.concat([data_rest,data_encode], axis= 1)

In [7]:
data_train, data_test= train_test_split(Data, test_size= 0.33, random_state= 4)
X2_train= data_train.drop("y", axis= 1)
Y2_train= data_train["y"]
X2_test= data_test.drop("y", axis=1)
Y2_test= data_test["y"]

In [8]:
scaler= StandardScaler()
scaler.fit(X2_train)
X2_train= scaler.transform(X2_train)
X2_test= scaler.transform(X2_test)

In [9]:
rbf = RBF(6) 
rbf.fit(X2_train,Y2_train)
result2 = rbf.predict(X2_test)

print('accuracy: ',accuracy_score(result2,Y2_test))
print('confusion_matrix: \n',confusion_matrix(result2,Y2_test))

accuracy:  0.8895442359249329
confusion_matrix: 
 [[13136  1540]
 [  108   136]]


### Dataset 3

In [10]:
from sklearn.datasets import load_digits
data=load_digits()

In [11]:
x3 = data['data']
y3 = data['target']

In [12]:
from sklearn.model_selection import train_test_split as sklearn_train_test_split
x3_train, x3_test, y3_train, y3_test =sklearn_train_test_split(x3, y3, test_size=0.3, random_state=42)

In [13]:
rbf = RBF(6) 
rbf.fit(x3_train,y3_train)
result3 = rbf.predict(x3_test)

print('accuracy: ',accuracy_score(result3,y3_test))
print('confusion_matrix: \n',confusion_matrix(result3,y3_test))

accuracy:  0.17592592592592593
confusion_matrix: 
 [[ 0  0  0  0  0  0  0  0  0  0]
 [ 0  6  0  0  0  0  0  0  0  0]
 [ 0  4  0  0  0  0  0  0  0  0]
 [ 0  3 15  0  9  4  8  0  0  0]
 [32 30 24 12 46 39 19  7 23 13]
 [21  7  8 40  5 22 21  8 19 41]
 [ 0  0  0  2  0  1  5 15  1  5]
 [ 0  0  0  0  0  0  0 16  0  0]
 [ 0  0  0  0  0  0  0  9  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]]
